// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR1aeEZa435pnTeKqWRHezJzbjISv6Dac',
    appId: '1:303813352822:web:e06d6c34a819201b8fae57',
    messagingSenderId: '303813352822',
    projectId: 'trials-linkedin',
    authDomain: 'trials-linkedin.firebaseapp.com',
    storageBucket: 'trials-linkedin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEvKS0ruIENTChQBNJyITsSyfadziINe4',
    appId: '1:303813352822:android:5cdc0c527f9d7ce38fae57',
    messagingSenderId: '303813352822',
    projectId: 'trials-linkedin',
    storageBucket: 'trials-linkedin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOrOq7TPMHrjlZfw5QoBJLWMdad4PJqQc',
    appId: '1:303813352822:ios:a63efa5cc1590b118fae57',
    messagingSenderId: '303813352822',
    projectId: 'trials-linkedin',
    storageBucket: 'trials-linkedin.appspot.com',
    androidClientId: '303813352822-7nrvu929incu9cs31sdq75tmbj3c7tou.apps.googleusercontent.com',
    iosClientId: '303813352822-ao9hc1h2449egtr2ghm92t94rci07c35.apps.googleusercontent.com',
    iosBundleId: 'com.example.samirFlutterUiChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOrOq7TPMHrjlZfw5QoBJLWMdad4PJqQc',
    appId: '1:303813352822:ios:a63efa5cc1590b118fae57',
    messagingSenderId: '303813352822',
    projectId: 'trials-linkedin',
    storageBucket: 'trials-linkedin.appspot.com',
    androidClientId: '303813352822-7nrvu929incu9cs31sdq75tmbj3c7tou.apps.googleusercontent.com',
    iosClientId: '303813352822-ao9hc1h2449egtr2ghm92t94rci07c35.apps.googleusercontent.com',
    iosBundleId: 'com.example.samirFlutterUiChallenge',
  );
}
